interval: "10m"
age: 
  identity: "keys/key.txt"
  recipients:
    - "age1nuxu3q9wr5wrd53dj8hj5flhz86q2dpjyuq7agseh0wzwq5t696s2dm0ht"
statePath: ".nox-state.json"
defaultRepo: git@github.com:ShorkBytes/nox-secrets.git

apps:
  debug:
    branch: main
    files:
      - path: debug/debug.age
        output: ./secrets/.env

  debug2:
    branch: main
    repo: git@github.com:ShorkBytes/nox-secrets.git
    files:
      - path: debug/debug.age
        output: ./secrets/debug2.env