interval: "10m"
age: 
  identity: "keys/key.txt"
  recipients:
    - "age1qq5sazxv755u2vs5ulyl486jxhlg7ztrvm27nya47aln668xldkqsm4kn5"
statePath: ".nox-state.json"
defaultRepo: git@github.com:ShorkBytes/nox-secrets.git

apps:
  debug:
    branch: main
    files:
      - path: debug/debug.age
        output: ./secrets/.env

  debug2:
    branch: main
    repo: git@github.com:ShorkBytes/nox-secrets.git
    files:
      - path: debug/debug.age
        output: ./secrets/debug2.env